name: Run lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  vue-lint:
    name: Eslint on Vue3 package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - run: yarn install
      - run: npx turbo generated-components --filter=./packages/vue3 && npx turbo lint --filter=./packages/vue3